[simulation]
tracing_accuracy = 0.4

[experiment]
name = "low_tracing_accuracy"
runs_per_config = 8
steps_per_run = 200
random_seed_base = 100

[experiment.sweeps]
gas_fee_share_rate = [0.002, 0.005]
funding_split_fraction = [0.01, 0.02]
